version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - mysql
    volumes:
      - ./app:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
